/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mscSidebar: [
    "msc/mestrado",
    {
      type: 'category',
      label: 'Algoritmos em Grafos',
      items: [
        {
          type: 'autogenerated',
          dirName: 'msc/algoritmos_em_grafos'
        }
      ]
    },
    {
      type: 'category',
      label: 'Computação Gráfica',
      items: [
        {
          type: 'autogenerated',
          dirName: 'msc/computacao_grafica'
        }
      ]
    },    
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
